export const LIST_ALL = 'LIST_ALL'
export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_STATUS = 'UPDATE_STATUS'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const SAVE_TASK = 'SAVE_TASK'


export const TOGGLE_FORM = 'TOGGLE_FORM'
export const CLOSE_FORM = 'CLOSE_FORM'
export const OPEN_FORM = 'OPEN_FORM'

export const SET_TASK_EDITING_DATA = 'SET_TASK_EDITING_DATA'
export const UPDATE_TASK_EDITING_DATA = 'UPDATE_TASK_EDITING_DATA'
export const CLEAR_TASK_EDITING_DATA = 'CLEAR_TASK_EDITING_DATA'

export const SET_KEY_WORD = 'SET_KEY_WORD'

export const SET_SORT_OPTIONS = 'SET_SORT_OPTIONS'
